packages:
  - examples/**
  - docs
  - client
catalog:
  nuxt: ^4.4.4
  vite: npm:@voidzero-dev/vite-plus-core@0.1.21-alpha.6
  vite-plugin-inspect: ^11.3.3
  vite-plus: 0.1.21-alpha.6
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.21-alpha.6

ignoreWorkspaceRootCheck: true
overrides:
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
