packages:
  - examples/**
  - docs
  - client
catalog:
  nuxt: ^4.4.4
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vite-plugin-inspect: ^11.3.3
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1856'
  vitest: '4.1.9'

ignoreWorkspaceRootCheck: true
overrides:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vitest: '4.1.9'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
  - '@sveltejs/kit'
  - sharp
  - vue-demi
  - svelte-preprocess
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
