packages:
  - examples/**
  - docs
  - client
catalog:
  nuxt: ^4.4.4
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1703'
  vite-plugin-inspect: ^11.3.3
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1703'
  vitest: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1703'

ignoreWorkspaceRootCheck: true
overrides:
  vitest: 'catalog:'
  '@voidzero-dev/vite-plus-core': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1703'
  '@voidzero-dev/vite-plus-test': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1703'
  '@voidzero-dev/vite-plus-prompts': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-prompts@1703'
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - vitest
  - '@vitest/*'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
